name: Build and Run first workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build C++ program
      run: g++ -o myprogram sum.cpp
      shell: bash

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram
        path: ./myprogram

  run:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: myprogram

    - name: Execute Program
      run: |
        chmod +x myprogram
        ./myprogram
      
